language: java
jdk:
- oraclejdk8
os:
- linux
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.gradle"
before_script:
- git fetch
script:
- "./gradlew clean build"
- "./pack.sh"
after_success:
- git config user.email "marcoveluscek@gmail.com"
- git config user.name "mvelusce"
- git add . 
- git status 
- git commit -m "Travis build"
- git push -f https://mvelusce:$GH_TOKEN@github.com/mvelusce/recipe-book.git master
