language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

env:
  global:
    - GH_REPO="github.com:mvelusce/recipe-book.git"

before_script:
  - git fetch

script:
  - ./gradlew clean build
  - ./pack.sh

after_success:
  - git config user.email "travis@travis-ci.org"
  - git config user.name "Travis CI"
  - git add .
  - git commit -m "New build"
  - git push -f -q "https://mvelusce:${GITHUB_API_KEY}@${GH_REPO}" master > /dev/null 2>&1
