language: java
jdk:
- oraclejdk8
os:
- linux
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.gradle"
before_script:
- git pull origin master
script:
- "./gradlew clean build"
after_success:
- git config user.email "marcoveluscek@gmail.com"
- git config user.name "mvelusce"
- git pull origin master
- "./pack.sh"
- git add --all
- git status 
- git commit -m "Travis build"
- git push -f https://mvelusce:$GH_TOKEN@github.com/mvelusce/recipe-book.git master
