language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

before_script:
  - git fetch

script:
  - ./gradlew clean build
  - ./launch4j/launch4j launch4j.xml
  - ./pack.sh

after_script:
  - git add .
  - git config user.email "${GIT_EMAIL}"
  - git config user.name "${GIT_NAME}"
  - git commit -m "New build"
  - git push -f "${GIT_URL}" master
