spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./db/recipes:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    password:
    initialize: true
    platform: prod
  jpa:
    ddl-auto: validate
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  contextPath: /recipe-book
  port: 9000

logging:
   file: ./log/recipe-book.log
   level:
      #ROOT: DEBUG
      #org.springframework: 'OFF'
      com.mvelusce: 'INFO'
