spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    initialize: true
    platform: development
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    ddl-auto: validate
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  contextPath: /recipe-book
  port: 9000

logging:
   file: ./log/recipe-book-dev.log
   level:
      #ROOT: DEBUG
      #org.springframework: 'OFF'
      com.mvelusce: 'DEBUG'
