spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./db/recipes;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    password:
    initialize: true
    platform: prod
  jpa:
    ddl-auto: validate
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  contextPath: /recipe-book
  port: 9000
